# Generated by Django 5.0.6 on 2024-07-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_team_team_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="coach",
        ),
        migrations.AddField(
            model_name="coach",
            name="team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach",
                to="users.team",
            ),
        ),
    ]
