# Generated by Django 5.0.6 on 2024-07-07 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_team_coach_coach_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="team_size",
        ),
    ]
