# Generated by Django 5.0.6 on 2024-07-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_team_team_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_size",
            field=models.PositiveIntegerField(default=10, verbose_name="Team Size"),
        ),
    ]
