# Generated by Django 5.0.6 on 2024-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_team_team_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="average_score",
            field=models.IntegerField(default=0, verbose_name="Average Score"),
        ),
        migrations.AlterField(
            model_name="player",
            name="num_games",
            field=models.IntegerField(default=0, verbose_name="Number of Games Played"),
        ),
    ]
