# Generated by Django 5.0.6 on 2024-07-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("coach", "Coach"),
                    ("player", "Player"),
                    ("league_admin", "League Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
