# Generated by Django 5.0.6 on 2024-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_tournament_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
