# Generated by Django 5.0.6 on 2024-07-08 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_tournament_current_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_eliminated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="users.tournament",
            ),
        ),
    ]
